- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/TextInput/TextInputViewController.swift
Moving the done button above the keyboard on the text input screen from left to right.
> feat: move keyboard done button to right

- .github/workflows/quality-report.yml
Updated the .yml to use the correct scheme previously this workflow was using the package scheme, when a demo project was introduced with a new scheme to help test UIViewControllers the PR workflow was updated but this one was left out this PR will fix that.
~Please include iPod Touch, iPhone SE and iPhone 11 as a minimum.~
> fix: quailty-report.yml uses Demo scheme

- Sources/GDSCommon/Extensions/UIKit/UIView+BorderExtension.swift
The border thickness was too thin and not appearing in some situations.
> fix: adjust default border width

- Sources/GDSCommon/Extensions/UIKit/UIView+BorderExtension.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Components/DatePickerViewModel.swift
This is to prevent multiple borders being drawn that overlap each other if developer / consumers of this were to for example pass in to the method:
`[.top, .top, .bottom, .bottom, .bottom]`
By the parameter now being a set, each member has to be unique so the resulting collection will only contain a single item of each edge.
Also changed `UIDatePickerStyle` property to be public to be accessible outside package.
> chore: changed border edge from array to set

- GDSCommon-Demo/GDSCommon-Demo/Extensions/ViewControllerInitialiser+Extensions.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockGDSInstructionsViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSInstructionsViewControllerTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/MockGDSInstructionsViewModel.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/GDSInstructions/GDSInstructionsViewController.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/GDSInstructions/GDSInstructionsViewModel.swift
This brings the screen in line with other recently added screens and allows the ability to dismiss the screen.
> feat: added optional right bar button item to Instructions Screen Pattern

- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockButtonViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockInstructionWithImageViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockOptionViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSInstructionsViewControllerTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/InstructionsWithImageViewControllerTests.swift
- Sources/GDSCommon/UI/SwiftUI/SharedViews/Buttons/ButtonView.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Buttons/ButtonIconViewModel.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Buttons/ButtonViewModel.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Components/BulletView.xib
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/GDSInstructions/GDSInstructionsViewController.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/InstructionsWithImage/InstructionsWithImage.xib
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/InstructionsWithImage/InstructionsWithImageViewController.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/InstructionsWithImage/InstructionsWithImageViewModel.swift
- Tests/GDSCommonTests/ComponentTests/Mocks/MockButtonViewModel.swift
feat: adding-optional-parameters-for-image-instructions
We have no way of adding an icon to the secondary button, on the Instructions View Controller. This PR is to enable that so we can add an icon when using that view from GDS Common.
This also adds the option to open the GDSInstructions view modally, and with an optional second button.
> feat!: adding-optional-parameters-for-image-instructions

- GDSCommon-Demo/GDSCommon-DemoTests/InstructionsWithImageViewControllerTests.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/InstructionsWithImage/InstructionsWithImageViewController.swift
fix: adding missing icon check in Primary Button
> fix: adding missing icon check in Primary Button

- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockQRScanningViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
- GDSCommon-Demo/GDSCommon-DemoTests/ScanningViewControllerTests.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/Scanner/QRScanningViewModel.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/Scanner/ScanningViewController.swift
DCMAW-7333: iOS | QR Scanner - Add Cancel Button
Added right bar button item to scanner screen.
> feat: added right bar button to qr scanner

- GDSCommon-Demo/GDSCommon-DemoTests/ScanningViewControllerTests.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/Scanner/ScanOverlayView.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/Scanner/ScanningViewController.swift
- Tests/GDSCommonTests/ScanOverlayViewTests.swift
This PR aims to remove the white overlay that appears on the QR code scanner page. The text has also been changed to appear bold and white in dark and light mode.
This PR also contains the fix for [DCMAW-7370](https://govukverify.atlassian.net/browse/DCMAW-7370).
[DCMAW-7370]: https://govukverify.atlassian.net/browse/DCMAW-7370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: QR scanner has incorrect design

- Sources/GDSCommon/UI/UIKit/SharedViews/BaseViewController.swift
In order to initialise the `BaseViewController` and therefore use outside of `GDSCommon` the init needs to be `public`.
~- [ ] Written Unit and Integration tests if needed~
~- [ ] Met all accessibility requirements?~
~- [ ] Checked VoiceOver can navigate your new code~
~- [ ] Checked a user can navigate only using a keyboard around your new code~
> fix: change access control on `BaseViewController` init to be public

- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/GDSError/GDSErrorViewController.swift
The error view controller's view model property is private and therefore can't be tested outside the package. This is needed for testing our project code to tell which error screens are shown.
~- [ ] Written Unit and Integration tests if needed~
~- [ ] Met all accessibility requirements?
> fix: allowing error view model to be read outside the package

- Sources/GDSCommon/UI/UIKit/SharedViews/BaseViewController.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/ListOptions/ListOptionsViewController.swift
When this was tested locally it works reliably without `@MainActor` but the behaviour is unreliable when running from a remote package (it seems unexpected there would be a difference in behaviour)
~- [ ] Met all accessibility requirements?~
~- [ ] Checked VoiceOver can navigate your new code~
~- [ ] Checked a user can navigate only using a keyboard around your new code~
> fix: adding `@MainActor` to do VoiceOverFocus on main queue

- .swiftlint.yml
- GDSCommon-Demo/GDSCommon-DemoTests/ScanningViewControllerTests.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/BaseViewController.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/Scanner/ScanningViewController.swift
Moving the `VoiceOverFocus` functionality to the `viewWillAppear` lifecycle method temporarily (until all pipelines are on Xcode 15 or later and can use `viewIsAppearing`)
Also removed `VoiceOverFocus` conformance from `ScanningViewController` because there seems to be a lifecycle defect there.
~- [ ] Met all accessibility requirements?~
~- [ ] Checked VoiceOver can navigate your new code
~- [ ] Checked a user can navigate only using a keyboard around your new code~
> fix: move notification post to viewWillAppear temporarily

- .github/workflows/pull-request.yml
- .github/workflows/quality-report.yml
- Sources/GDSCommon/UI/UIKit/SharedViews/BaseViewController.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/Scanner/ScanningViewController.swift
This includes: 
* setting Xcode-select to 15.1 which is now available
* setting `BaseViewController` lifecycle methods to `open` access control on so they can be overridden if required
> fix: reimplement `viewIsAppearing` method for voice over focus

- GDSCommon-Demo/GDSCommon-Demo.xcodeproj/project.pbxproj
- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockBulletViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockGDSInstructionsViewModel.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSInstructionsViewControllerTests.swift
- Sources/GDSCommon/README.md
- Sources/GDSCommon/UI/UIKit/SharedViews/Components/BulletView.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Components/BulletViewModel.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/Scanner/ScanningViewController.swift
- Tests/GDSCommonTests/ComponentTests/BulletViewTests.swift
A change to allow us to pass through an optional titleFont parameter to change how the BulletView title looks. We have set a default font so that this does not affect existing implementations.
> fix: allowing us to change the font of title on BulletView

- GDSCommon-Demo/GDSCommon-Demo.xcodeproj/project.pbxproj
- GDSCommon-Demo/GDSCommon-DemoTests/GDSInformationViewControllerTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/Mocks/MockGDSInformationViewModel.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/GDSInformation/GDSInformation.xib
We found an issue so that even if we set the icon in the view model of GDSInformationViewController, the icon displayed anyway. Identified that it was due to the icon name being set in the storyboard.
Have renamed various things to keep the code style consistent, and added missing tests which check that the icon is displayed/hidden as required.
> fix: ensuring icon isn't set in storyboard

- Sources/GDSCommon/UI/UIKit/SharedViews/BaseViewController.swift
Changing these parameters to being optional matches the super init and will allow the `BaseViewController` to be used for view controllers build programmatically (ie, without a `xib` / `nib`)
~- [ ] Met all accessibility requirements?~
~- [ ] Checked VoiceOver can navigate your new code~
~- [ ] Checked a user can navigate only using a keyboard around your new code~
> fix: update base view controller init

- .github/workflows/pull-request.yml
- .github/workflows/quality-report.yml
- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockButtonViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockModalInfoViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
- GDSCommon-Demo/GDSCommon-DemoTests/ModalInfoViewControllerTests.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Buttons/PageButtonViewModels.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/ModalInfoView/ModalInfoView.xib
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/ModalInfoView/ModalInfoViewController.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/ModalInfoView/ModalInfoViewModel.swift
- Tests/GDSCommonTests/ComponentTests/DialogViewTests.swift
Add a text button to ModalInfoView, appearing below body text.   This will be used by the OneLogin app to link to the privacy policy
> feat: dcmaw-8571 analytics privacy link

- Sources/GDSCommon/Extensions/UIKit/UIColor+Extensions.swift
- Sources/GDSCommon/Resources/Colours.xcassets/Colours/Red.colorset/Contents.json
Add "Red" colour as defined by designs.  Seems to have been missed out in original setup.
> fix: dcmaw-8695: Add gdsRed colour to assets

- GDSCommon-Demo/GDSCommon-DemoTests/BaseViewControllerTests.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/BaseViewController.swift
Adding this identifier which will enable consumers to access the right bar button element in `BaseViewController` when writing UI tests
~Please include iPod Touch, iPhone SE and iPhone 11 as a minimum.~
> fix: added accessibility identifier to right bar button

- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockListViewModel.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSListOptionsViewControllerTests.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/GDSListOptions/GDSListOptionsViewController.swift
This PR moved where the result action is called, moving from the primary button action into the `didSelect` table view delegate methods so it is no longer tied to primary button.  
~Please include iPod Touch, iPhone SE and iPhone 11 as a minimum.~
> fix: refactored when results action is called

- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/GDSListOptions/GDSListOptions.xib
Through Design QA it was identified that the spacing in the list view is not correct and did not follow the Figma designs. This PR updates the spacing in the `GDSListOptions` view. 
Previously the stack used to display the `title` and `body` text had a spacing of 12, it is now 16.
Previously the stack used to display the `tableTitle` and `table` had a spacing of 5, it is now 16.
- [] ~Written Unit and Integration tests if needed~
- [] Met all accessibility requirements?
> fix: updated spacing to 16

- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/GDSListOptions/GDSListOptions.xib
This PR changes the a stack views (the empty stack for childViews) layout margins to language directional with an offset of 16 points in leading and trailing margins.
> fix: changed layout margin in GDSListOptions

- GDSCommon-Demo/GDSCommon-DemoTests/IntroViewControllerTests.swift
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/IntroView/IntroView.xib
- Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/IntroView/IntroViewController.swift
Disabling/enabling the intro view button has not been working since this screen was added to the package, this PR addresses that adding a public method to disable the loading state of the button.
> fix: disable/enable intro view button

- Sources/GDSCommon/Utilities/GDSLocalisedString.swift
- Tests/GDSCommonTests/GDSLocalisedStringTests.swift
**DCMAW-9219**
GDSLocalisedString now conforms to equatable so it can be compared:
```swift
let stringOne = GDSLocalisedString(stringKey: "firstNonStringLiteral", "one", "two", "three")
let stringTwo = GDSLocalisedString(stringKey: "secondNonStringLiteral", "one", "two", "three")
if stringOne == stringTwo {
// do something
}
```
> feat: add equatable conformance to GDSLocalisedString

- GDSCommon-Demo/GDSCommon-DemoTests/ModalInfoViewControllerTests.swift
> chore: added missing tests for primary button icon in modal info view

- Sources/GDSCommon/Patterns/GDSInstructions/GDSInstructionsViewController.swift
Updated `GDSInstructionsViewController` viewModel property access to public let, this is so we can access the viewModel safely without changing it
> chore: updated viewModel access to public let

- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockErrorViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSErrorViewControllerTests.swift
- Sources/GDSCommon/Patterns/GDSError/GDSError.xib
- Sources/GDSCommon/Patterns/GDSError/GDSErrorViewController.swift
- Sources/GDSCommon/Patterns/GDSError/GDSErrorViewModel.swift
- Sources/GDSCommon/Patterns/README.md
To update ID Check SDK to use the Common ErrorView we needed to update it with a third button. To avoid a breaking change a separate protocol has been made to set the third button
> feat: updated ErrorView with a third button

- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockErrorViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSErrorViewControllerTests.swift
- Sources/GDSCommon/Patterns/GDSError/GDSErrorViewController.swift
- Sources/GDSCommon/Patterns/GDSError/GDSErrorViewModel.swift
- Sources/GDSCommon/Patterns/README.md
Previously every GDSError screen had an icon image as part of the screen. This PR implements non-breaking changes for the package to deprecate the `GDSErrorViewModel` and allowing the use of two protocols; `GDSErrorViewModelV2` & `GDSErrorViewModelWithImage`
> feat: updating GDSError to optionally have icon

- Sources/GDSCommon/Components/ContentTile/GDSContentTileView.swift
- Sources/GDSCommon/Components/ContentTile/GDSContentTileView.xib
- Tests/GDSCommonTests/ComponentTests/GDSContentTileViewTests.swift
When conforming to the content tile, it was noticed that the secondary button appeared white. This is likely to be because the colour was not set correctly here. This PR aims to set the colour of the secondary button in the correct way.
~- [] Met all of the acceptance criteria specified in the user story on Jira~
> fix: properly setting button colour

- xccov-to-sonarqube-generic.sh
The sonar scanning script is outdated and there is [a new one which should be used](https://github.com/SonarSource/sonar-scanning-examples/blob/master/swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh). This PR updates that script.
~- [ ] Met all of the acceptance criteria specified in the user story on Jira~
~- [ ] Reviewed your own code to ensure you are following the style guidelines~
~- [ ] Ran the app and tested the feature on a range of device sizes
Please include iPod Touch, iPhone SE and iPhone 11 as a minimum.~
~- [ ] Written Unit and Integration tests if needed~
~- [ ] Met all accessibility requirements?
> ci: update sonar script

- GDSCommon-Demo/GDSCommon-DemoTests/GDSCentreAlignedScreenTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/Mocks/MockGDSCentreAlignedViewModel.swift
- Sources/GDSCommon/Patterns/GDSInformation/GDSCentreAlignedScreen.swift
- Sources/GDSCommon/Patterns/GDSInformation/GDSInformationViewModelV2.swift
Added in an else block to hide the image if the viewModel does not conform to GDSCentreAlignedViewModelWithImage and added in tests for image being displayed and hidden. 
Updated the deprecated warnings to include GDS prefix.
> feat: fix GDSCentreAlignedScreen image

- Sources/GDSCommon/Patterns/IntroView/IntroView.xib
remove placeholder text from the bottom button in IntroView so a copy of ‘Continue’ is not shown when the user opens the app and the ‘Sign in’ button gets displayed.
#Ticket
[DCMAW-10668](https://govukverify.atlassian.net/browse/DCMAW-10668)
#Evidence
https://github.com/user-attachments/assets/232810d8-285f-4d95-91f8-61e73b8eaaf7
[DCMAW-10668]: https://govukverify.atlassian.net/browse/DCMAW-10668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove placeholder text from the bottom button in IntroView

- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockButtonViewModel.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSCentreAlignedScreenTests.swift
- Sources/GDSCommon/Patterns/GDSInformation/GDSCentreAlignedScreen.swift
As part of the work on DCMAW-11082 and implementing the MAM handback screen for the ID Check V2, the primary button for the Centre Aligned Screen needed an icon property to be set in the view controller. Therefore, this PR sets the icon if it is present in the view model. 
_Note: This will display in all mocks in the demo app where `MockButtonViewModel.primary` is used, but it is an optional property on the actual view model itself_
> fix: displays icon if present on centre aligned screen primary button

- GDSCommon-Demo/GDSCommon-Demo.xcodeproj/project.pbxproj
- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockBulletViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockButtonViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockErrorViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockOptionViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
- GDSCommon-Demo/GDSCommon-DemoTests/ErrorScreenTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSCentreAlignedScreenTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSInstructionsViewControllerTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/Mocks/MockGDSErrorViewModelV3.swift
- Sources/GDSCommon/Components/BodyTextViewModel.swift
- Sources/GDSCommon/Components/BulletView/BulletViewModel.swift
- Sources/GDSCommon/Components/Buttons/ButtonViewModel.swift
- Sources/GDSCommon/Components/ScreenBodyItem.swift
- Sources/GDSCommon/Patterns/GDSError/ErrorScreenImage.swift
- Sources/GDSCommon/Patterns/GDSError/GDSErrorScreen.swift
- Sources/GDSCommon/Patterns/GDSError/GDSErrorViewController.swift
- Sources/GDSCommon/Patterns/GDSError/GDSErrorViewModel.swift
- Sources/GDSCommon/Patterns/GDSInformation/GDSCentreAlignedScreen.swift
- Sources/GDSCommon/Patterns/README.md
- Sources/GDSCommon/Patterns/VoiceOverFocus.swift
- Sources/GDSCommon/Styles/Strings/cy.lproj/Localizable.strings
- Sources/GDSCommon/Styles/Strings/en.lproj/Localizable.strings
- Sources/GDSCommon/Utilities/Extensions/UIKit/UIControl+Extensions.swift
- Sources/GDSCommon/Utilities/Extensions/UIKit/UIStackView+Extensions.swift
- Sources/GDSCommon/Utilities/Extensions/UIKit/UIView+Extensions.swift
- Tests/GDSCommonTests/ButtonViewModelTests.swift
- Tests/GDSCommonTests/ComponentTests/Mocks/MockButtonViewModel.swift
This PR adds a new code only generated screen to match requirements for the new Error screen pattern.
https://govukverify.atlassian.net/browse/DCMAW-11848
https://github.com/user-attachments/assets/deba362e-e5b0-42b0-942e-4d89f5187c84
https://github.com/user-attachments/assets/af9e909f-7368-4b39-b2a6-170b469bf6ff
> feat: dcmaw-11848 new error pattern error screen

- GDSCommon-Demo/GDSCommon-DemoTests/ErrorScreenTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSCentreAlignedScreenTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSInstructionsViewControllerTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/ModalInfoViewControllerTests.swift
- Sources/GDSCommon/Patterns/ModalInfoView/ModalInfoViewController.swift
Following a missed requirement in [DCMAW-7383](https://govukverify.atlassian.net/browse/DCMAW-7873), this PR aims to add accessibility hints to the buttons on the `ModalInfoViewController`.
~- [ ] Created a `draft` pull request if it is not yet ready for review~
~- [ ] Ran the app and tested the feature on a range of device sizes
Please include iPod Touch, iPhone SE and iPhone 11 as a minimum.~
~- [ ] Checked a user can navigate only using a keyboard around your new code~ 
[DCMAW-7383]: https://govukverify.atlassian.net/browse/DCMAW-7383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: adding accessibility hint to modal info buttons

- Sources/GDSCommon/Components/BodyTextViewModel.swift
- Sources/GDSCommon/Components/BulletView/BulletViewModel.swift
- Sources/GDSCommon/Components/Buttons/ButtonViewModel.swift
- Sources/GDSCommon/Components/ScreenBodyItem.swift
- Sources/GDSCommon/Patterns/GDSError/GDSErrorScreen.swift
- Tests/GDSCommonTests/ComponentTests/BulletViewTests.swift
- Tests/GDSCommonTests/ComponentTests/Image+ExtensionsTests.swift
- Tests/GDSCommonTests/ComponentTests/Mocks/MockBulletViewModel.swift
- Tests/GDSCommonTests/ScreenBodyItemTests.swift
************
This is technically a breaking change. Would like to merge without bumping the major version number as this is a tweak on a new feature. 
************
2 changes here:
- Changing the body text content item to use GDSLocalisedString instead of String
- Updating ScreenBodyItem protocol to have a `uiView` property to simplify its use and allow for adding of custom content items from consumer codebases
> fix: updating screen body item protocol and body text item

- Sources/GDSCommon/Utilities/URLOpener.swift
Receiving Swift 6 warnings about passing UIApplication into a nonisolated context for the URLOpener protocol.
[UIApplication](https://developer.apple.com/documentation/uikit/uiapplication/open(_:options:completionhandler:)) is MainActor isolated so ensuring the protocol matches that
~- [ ] Written Unit and Integration tests if needed~
~- [ ] Met all accessibility requirements?
> fix: adding MainActor isolation to URLOpener

- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockButtonViewModel.swift
- Sources/GDSCommon/Components/Buttons/RoundedButton.swift
When using a keyboard, the scan QR code icon has low colour contrast in hover state. The expected behaviour is that content should be legible whatever state the UI is in and the icon image should match text colour.
This is under the SC 1.4.13 content on hover and 1.4.3 colour contrast of the WCAG success criteria and they are both level AA issues.
The change here ensures that when we hover over the primary button with an icon, we see the icon as the same colour as the text.
Before:
https://github.com/user-attachments/assets/e8af3c7a-643a-466d-be60-5c8412bbe460
After:
https://github.com/user-attachments/assets/1964a3f8-4c8e-4e92-9171-6cdb0ec34c99
Please include iPod Touch, iPhone SE and iPhone …
> fix: fixing low contrast on button icon

- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockGDSCentreAlignedViewModel.swift
- GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
- Sources/GDSCommon/Patterns/GDSInformation/GDSCentreAlignedScreen.swift
When the bottom stack wasn't needed, 3 empty views were being added to it. This caused problems with layout as those views expanded to occupy a lot of screen space, preventing the title from being vertically centred.
This PR makes the bottom stack sub-views optional and only adding them to the stack if they are needed.
> fix: conditionally adding bottom stack view subviews

- Sources/GDSCommon/Components/ContentTile/GDSContentTileView.swift
- Sources/GDSCommon/Components/ContentTile/GDSContentTileViewModel.swift
- Sources/GDSCommon/Utilities/Extensions/UIKit/UIFont+GDS.swift
- Tests/GDSCommonTests/ComponentTests/GDSContentTileViewTests.swift
> feat: add new font for content tile title label

- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockButtonViewModel.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSCentreAlignedScreenTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSErrorScreenTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSLeftAlignedScreenTests.swift
- Sources/GDSCommon/Patterns/GDSError/GDSErrorScreen.swift
- Sources/GDSCommon/Patterns/GDSInformation/GDSCentreAlignedScreen.swift
- Sources/GDSCommon/Patterns/GDSLeftAligned/GDSLeftAlignedScreen.swift
The logic for having a loading animator on the button in the centre aligned view was missing, this PR adds it and also a public function to reset the button should we need to in the cases of a modal popover from the button event being subsequently dismissed.
> fix: button loading logic

- GDSCommon-Demo/GDSCommon-DemoTests/GDSInstructionsViewControllerTests.swift
- GDSCommon-Demo/GDSCommon-DemoTests/Mocks/MockGDSInstructionsViewModel.swift
- Sources/GDSCommon/Patterns/GDSInstructions/GDSInstructionsViewController.swift
- Sources/GDSCommon/Patterns/GDSInstructions/GDSInstructionsViewModel.swift
A bug was discovered in ID Check ([ticket](https://govukverify.atlassian.net/browse/DCMAW-12655)) when upon dismissing the abort flow and going back, the primary button on `GDSInstructionsViewController` was disabled. 
This PR creates a new view model, `GDSInstructionsViewModelDisableButton`, which if conformed to will disable the primary button. Otherwise, the primary button is enabled.
> fix: enables primary button when returning to GDSInstructionsViewController

- Sources/GDSCommon/Components/ContentTile/GDSContentTileView.swift
- Sources/GDSCommon/Styles/Strings/cy.lproj/Localizable.strings
- Sources/GDSCommon/Styles/Strings/en.lproj/Localizable.strings
- Tests/GDSCommonTests/ComponentTests/GDSContentTileViewTests.swift
https://github.com/user-attachments/assets/4a705f80-d568-465c-899d-d25a3556e65e
https://github.com/user-attachments/assets/4f77d3d8-1a92-4477-9c7c-fd3f10ecb41a
> fix: announce "card" after content tile title

- GDSCommon-Demo.xcworkspace/xcshareddata/swiftpm/Package.resolved
- GDSCommon-Demo/GDSCommon-Demo/Mocks/MockErrorViewModel.swift
- GDSCommon-Demo/GDSCommon-DemoTests/GDSLeftAlignedScreenTests.swift
- Package.swift
- Sources/GDSCommon/Components/BodyContent/BodyTextViewModel.swift
- Sources/GDSCommon/Components/BodyContent/DividerViewModel.swift
- Sources/GDSCommon/Components/BulletView/BulletViewModel.swift
- Sources/GDSCommon/Patterns/GDSLeftAligned/GDSLeftAlignedScreen.swift
Added more ScreenBodyItems to support Document information screen updates
* BodyTextViewModel (updated to add optional minimumHeight to enable alignment with other items)
* DividerViewModel (new)
* GDSLeftAlignedScreen (updated to hide titlestackview when title is empty)
> feat: DCMAW-13401 - added more ScreenBodyItems

- GDSCommon-Demo/GDSCommon-DemoTests/GDSCentreAlignedScreenTests.swift
- Sources/GDSCommon/Patterns/GDSInformation/GDSCentreAlignedScreen.swift
Centre aligned screen title label incorrectly did not have dynamic type set.
https://govukverify.atlassian.net/browse/DCMAW-14082
> fix: dynamic type on title label

- Sources/GDSCommon/Components/ContentTile/GDSContentTileView.swift
- Tests/GDSCommonTests/ComponentTests/GDSContentTileViewTests.swift
Ticket: https://govukverify.atlassian.net/browse/DCMAW-13478
This aims to address an issue discovered with the `GDSContentTileView` primary button which could not be focused when using an external keyboard. This now allows the user to navigate with the arrow keys into the card and activate the button.
https://github.com/user-attachments/assets/963e568a-7384-4a55-a2a5-2361a27f0093 (taken from the TestWrapper ID Check app, red cell not included)
> fix: ContentTileCard's primary button keyboard focus fix

- .github/workflows/pull-request.yml
- .github/workflows/quality-report.yml
- Package.swift
- Tests/GDSCommonTests/ButtonStylesTests.swift
We've known that view inspector tests have failed when run against Xcode 16.3+ for a while. A recent view inspector update has allowed fixing of the unit tests so they now run successfully on 16.3 / 16.4.
This PR updates these unit tests so that the runner configuration can be updated to use Xcode and simulator versions currently available on Github.
> fix: updated view inspector tests
